version: 2.1

jobs:
  beginning_the_workflow:  # This runs automatically
    docker:
      - image: cimg/base:2023.03
    steps:
      - run:
          name: Beginning the Workflow
          command: echo "Workflow started."

  finish_data_request:  # Now requires approval before running
    type: approval

  get_analyst_sign_off:  # Still requires approval
    type: approval
    requires:
      - finish_data_request

  all_done:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run:
          name: All Done
          command: echo "Processing data..."

workflows:
  version: 2
  data_approval_workflow:
    jobs:
      - beginning_the_workflow:  # Runs automatically
          filters:
            branches:
              only:
                - main
      - finish_data_request:  # Needs approval before running
          requires:
            - beginning_the_workflow
          filters:
            branches:
              only:
                - main
      - get_analyst_sign_off:  # Still requires approval
          requires:
            - finish_data_request
          filters:
            branches:
              only:
                - main
      - all_done:
          requires:
            - get_analyst_sign_off
          filters:
            branches:
              only:
                - main
