version: 2.1

jobs:
  data_request:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run:
          name: Data Request
          command: echo "Data request completed."

  analyst_approval:
    type: approval
    requires:
      - data_request

  process_data:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run:
          name: Process Data
          command: echo "Processing data..."

workflows:
  version: 2
  data_approval_workflow:
    jobs:
      - data_request
      - analyst_approval:
          requires:
            - data_request
      - process_data:
          requires:
            - analyst_approval
    triggers:
      - pull_request:
          branches:
            - main
