version: 2.1

jobs:
  finish_data_request:  # Updated job name
    docker:
      - image: cimg/base:2023.03
    steps:
      - run:
          name: Finish Data Request  # Updated step display name
          command: echo "Data request completed."

  get_analyst_sign_off:  # Updated job name
    type: approval
    requires:
      - finish_data_request

  all_done:  # Updated job name
    docker:
      - image: cimg/base:2023.03
    steps:
      - run:
          name: All Done  # Updated step display name
          command: echo "Processing data..."

workflows:
  version: 2
  data_approval_workflow:
    jobs:
      - finish_data_request:
          filters:
            branches:
              only:
                - main
      - get_analyst_sign_off:
          requires:
            - finish_data_request
          filters:
            branches:
              only:
                - main
      - all_done:
          requires:
            - get_analyst_sign_off
          filters:
            branches:
              only:
                - main
