version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: Build
          command: echo "Building the project..."

  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: Run Tests
          command: echo "Running tests..."

  approval:
    type: approval
    requires:
      - test

  deploy:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: Deploy
          command: echo "Deploying the project..."

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - approval:
          requires:
            - test
      - deploy:
          requires:
            - approval
